{{- if .Values.velero.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: default-backup
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    ttl: {{ .Values.velero.ttl }}
{{- if .Values.velero.snapshotsEnabled }}
  volumeSnapshotLocations:
    - volume-snapshots
{{- end }}
{{- end }}
