# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "registry.ng.bluemix.net"
  Master:
    Readiness:
      InitialDelaySeconds: 600
    Liveness:
      InitialDelaySeconds: 660
      
jenkins-x-platform:
  dockerRegistry: "{{ .Requirements.cluster.registry }}"

docker-registry:
  enabled: false      
