external-dns:
  enabled: {{ .Requirements.ingress.externalDNS }}
  sources:
  - ingress
  provider: google
  google:
    serviceAccountSecret: external-dns-gcp-sa
 {{- if hasKey .Requirements.cluster "project" }}
    project: "{{ .Requirements.cluster.project }}"
 {{ end }}
  rbac:
    create: true
  domainFilters:
# loop over environments' ingresses and add each domain
{{- range .Requirements.environments }}
  {{- if .ingress.domain }}
  - "{{ .ingress.domain }}"
  {{- end }}
{{- end }}
